# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: histogram1d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='histogram1d.proto',
  package='physt',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11histogram1d.proto\x12\x05physt\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"p\n\x04Meta\x12\x12\n\naxis_names\x18\x01 \x03(\t\x12\x0e\n\x06missed\x18\x02 \x03(\x02\x12\x13\n\x0bmissed_keep\x18\x03 \x01(\x08\x12\x15\n\rphyst_version\x18\x04 \x01(\t\x12\x18\n\x10physt_compatible\x18\x05 \x01(\t\"5\n\tBinLimits\x12\x13\n\x0blower_limit\x18\x01 \x01(\x02\x12\x13\n\x0bupper_limit\x18\x02 \x01(\x02\"R\n\x08\x42innings\x12\x10\n\x08\x61\x64\x61ptive\x18\x01 \x01(\x08\x12\x14\n\x0c\x62inning_type\x18\x02 \x01(\t\x12\x1e\n\x04\x62ins\x18\x03 \x03(\x0b\x32\x10.physt.BinLimits\"\x98\x01\n\x0bHistogram1D\x12\x16\n\x0ehistogram_type\x18\x01 \x01(\t\x12!\n\x08\x62innings\x18\x02 \x01(\x0b\x32\x0f.physt.Binnings\x12\x13\n\x0b\x66requencies\x18\x03 \x03(\x02\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x0f\n\x07\x65rrors2\x18\x05 \x03(\x02\x12\x19\n\x04meta\x18\x06 \x01(\x0b\x32\x0b.physt.Meta\"3\n\x07Summary\x12(\n\x0chistograms1d\x18\x01 \x03(\x0b\x32\x12.physt.Histogram1Db\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_META = _descriptor.Descriptor(
  name='Meta',
  full_name='physt.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis_names', full_name='physt.Meta.axis_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='missed', full_name='physt.Meta.missed', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='missed_keep', full_name='physt.Meta.missed_keep', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='physt_version', full_name='physt.Meta.physt_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='physt_compatible', full_name='physt.Meta.physt_compatible', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=234,
)


_BINLIMITS = _descriptor.Descriptor(
  name='BinLimits',
  full_name='physt.BinLimits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower_limit', full_name='physt.BinLimits.lower_limit', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper_limit', full_name='physt.BinLimits.upper_limit', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=289,
)


_BINNINGS = _descriptor.Descriptor(
  name='Binnings',
  full_name='physt.Binnings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adaptive', full_name='physt.Binnings.adaptive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binning_type', full_name='physt.Binnings.binning_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bins', full_name='physt.Binnings.bins', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=373,
)


_HISTOGRAM1D = _descriptor.Descriptor(
  name='Histogram1D',
  full_name='physt.Histogram1D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='histogram_type', full_name='physt.Histogram1D.histogram_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binnings', full_name='physt.Histogram1D.binnings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequencies', full_name='physt.Histogram1D.frequencies', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='physt.Histogram1D.dtype', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors2', full_name='physt.Histogram1D.errors2', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='physt.Histogram1D.meta', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=528,
)


_SUMMARY = _descriptor.Descriptor(
  name='Summary',
  full_name='physt.Summary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='histograms1d', full_name='physt.Summary.histograms1d', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=581,
)

_BINNINGS.fields_by_name['bins'].message_type = _BINLIMITS
_HISTOGRAM1D.fields_by_name['binnings'].message_type = _BINNINGS
_HISTOGRAM1D.fields_by_name['meta'].message_type = _META
_SUMMARY.fields_by_name['histograms1d'].message_type = _HISTOGRAM1D
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.message_types_by_name['BinLimits'] = _BINLIMITS
DESCRIPTOR.message_types_by_name['Binnings'] = _BINNINGS
DESCRIPTOR.message_types_by_name['Histogram1D'] = _HISTOGRAM1D
DESCRIPTOR.message_types_by_name['Summary'] = _SUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'histogram1d_pb2'
  # @@protoc_insertion_point(class_scope:physt.Meta)
  ))
_sym_db.RegisterMessage(Meta)

BinLimits = _reflection.GeneratedProtocolMessageType('BinLimits', (_message.Message,), dict(
  DESCRIPTOR = _BINLIMITS,
  __module__ = 'histogram1d_pb2'
  # @@protoc_insertion_point(class_scope:physt.BinLimits)
  ))
_sym_db.RegisterMessage(BinLimits)

Binnings = _reflection.GeneratedProtocolMessageType('Binnings', (_message.Message,), dict(
  DESCRIPTOR = _BINNINGS,
  __module__ = 'histogram1d_pb2'
  # @@protoc_insertion_point(class_scope:physt.Binnings)
  ))
_sym_db.RegisterMessage(Binnings)

Histogram1D = _reflection.GeneratedProtocolMessageType('Histogram1D', (_message.Message,), dict(
  DESCRIPTOR = _HISTOGRAM1D,
  __module__ = 'histogram1d_pb2'
  # @@protoc_insertion_point(class_scope:physt.Histogram1D)
  ))
_sym_db.RegisterMessage(Histogram1D)

Summary = _reflection.GeneratedProtocolMessageType('Summary', (_message.Message,), dict(
  DESCRIPTOR = _SUMMARY,
  __module__ = 'histogram1d_pb2'
  # @@protoc_insertion_point(class_scope:physt.Summary)
  ))
_sym_db.RegisterMessage(Summary)


# @@protoc_insertion_point(module_scope)
